### ISSUE TITLE
[Bug]: 5.12.0 — #[Context] on a self-reference yields two Models sharing one schema name, breaking apidoc:dump

### ISSUE THREAD

**Issue by plantas** [nelmio/NelmioApiDocBundle#2799]
### Version

5.12.0 (works on 5.11.1)

### Description

After upgrading 5.11.1 → 5.12.0, `bin/console nelmio:apidoc:dump --format=json` fails:

```
User Warning: Multiple definitions for @OA\Property()->additionalProperties
     Using: \Repro\Entity\Category->permissions in .../src/Entity/Category.php
  Skipping: \Repro\Entity\Category->permissions in .../src/Entity/Category.php
```

Note that "Using" and "Skipping" point at the *same* property in the *same* file. The warning is
raised through swagger-php's `DefaultLogger` (`trigger_error`), which Symfony's error handler turns
into an `ErrorException`, so the command exits 1 — the docs cannot be dumped at all.

Two things combine here: a change in 5.12.0, and a pre-existing gap in `ModelRegistry::register()`.

#### Environment

| Q | A |
|---|---|
| NelmioApiDocBundle version | 5.12.0 (works on 5.11.1) |
| zircote/swagger-php version | 6.7.1 |
| Symfony version | 7.4.18 (reproducer), also seen on 8.1.6 |
| PHP version | 8.5.5 |

#### Standalone reproducer

Four files plus a `composer.json`. `composer install && php bin/console nelmio:apidoc:dump
--area=default --format=json` exits 1 on 5.12.0 and 0 on 5.11.1.

<details>
<summary><code>composer.json</code></summary>

```json
{
    "name": "repro/nelmio-schema-name-collision",
    "type": "project",
    "require": {
        "php": ">=8.2",
        "nelmio/api-doc-bundle": "5.12.0",
        "phpdocumentor/reflection-docblock": "^5.4",
        "symfony/console": "^7.2",
        "symfony/framework-bundle": "^7.2",
        "symfony/property-info": "^7.2",
        "symfony/serializer": "^7.2"
    },
    "autoload": { "psr-4": { "Repro\\": "src/" } },
    "config": { "allow-plugins": { "symfony/flex": false, "symfony/runtime": false } }
}
```

</details>

`src/Entity/Category.php`:

```php
<?php declare(strict_types=1);

namespace Repro\Entity;

use OpenApi\Attributes as OA;
use Symfony\Component\Serializer\Attribute\Context;
use Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer;

class Category
{
    // Any property whose #[OA\Property] carries a *nested* annotation makes the bug fatal.
    #[OA\Property(
        type: 'object',
        additionalProperties: new OA\AdditionalProperties(type: 'array', items: new OA\Items(type: 'string')),
    )]
    public ?array $permissions = null;

    /**
     * Self-reference whose #[Context] makes 5.12.0 build a second Model of this very class.
     *
     * @var Category[]
     */
    #[Context(context: [AbstractObjectNormalizer::ENABLE_MAX_DEPTH => true])]
    public array $relatedCategories = [];
}
```

`src/Controller/CategoryController.php`:

```php
<?php declare(strict_types=1);

namespace Repro\Controller;

use Nelmio\ApiDocBundle\Attribute\Model;
use OpenApi\Attributes as OA;
use Repro\Entity\Category;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

class CategoryController
{
    #[Route('/api/categories', methods: ['GET'])]
    #[OA\Response(
        response: 200,
        description: 'A category',
        content: new OA\JsonContent(ref: new Model(type: Category::class)),
    )]
    public function __invoke(): JsonResponse
    {
        return new JsonResponse([]);
    }
}
```

<details>
<summary><code>src/Kernel.php</code> and <code>bin/console</code></summary>

```php
<?php declare(strict_types=1);

namespace Repro;

use Nelmio\ApiDocBundle\NelmioApiDocBundle;
use Symfony\Bundle\FrameworkBundle\FrameworkBundle;
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;
use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;

class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    public function registerBundles(): iterable
    {
        yield new FrameworkBundle();
        yield new NelmioApiDocBundle();
    }

    protected function configureContainer(ContainerConfigurator $container): void
    {
        $container->extension('framework', [
            'secret' => 'repro',
            'http_method_override' => false,
            'router' => ['utf8' => true],
            'property_info' => ['enabled' => true],
            'serializer' => ['enabled' => true],
        ]);

        $container->extension('nelmio_api_doc', [
            'documentation' => ['info' => ['title' => 'Repro', 'version' => '1.0.0']],
            'areas' => ['default' => ['path_patterns' => ['^/api']]],
        ]);

        $container->services()
            ->set(Controller\CategoryController::class)
            ->public()
            ->tag('controller.service_arguments');
    }

    protected function configureRoutes(RoutingConfigurator $routes): void
    {
        $routes->import(__DIR__.'/Controller/', 'attribute');
    }
}
```

```php
#!/usr/bin/env php
<?php declare(strict_types=1);

use Repro\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;

require __DIR__.'/../vendor/autoload.php';

$kernel = new Kernel('dev', true);
$kernel->boot();

exit((new Application($kernel))->run());
```

</details>

Neither `#[Groups]` nor `#[MaxDepth]` is needed — `#[Context]` on the self-reference is enough. Note
that the generated doc is cached per area, so `rm -rf var/` between runs.

#### Cause

**1. 5.12.0 creates an extra `Model` for the same class.**

[#2722](https://github.com/nelmio/NelmioApiDocBundle/issues/2722) ("pass `#[Context]` attribute data
to property describers") merges the property's normalization context into the context handed to the
property describer:

```php
// ObjectModelDescriber::describe()
$propertyContext = array_merge($propertyContext, $attributesMetadata[$propertyName]->getNormalizationContextForGroups($modelGroups ?? []));
...
$this->describeProperty($types, $model, $property, $propertyName, $propertyContext);
```

The context is part of `Model::getHash()`, so for a **self-referencing** property annotated with
`#[Context]` the nested model is a *different* model than the root model of the same class, with the
same serializer groups.

**2. Both models then get the *same* schema name.**

`ModelRegistry::register()` generates the name, then runs the schema-dedup probe, and only reserves
the name in `components.schemas` at the very end:

```php
if (!isset($this->names[$hash])) {
    $this->names[$hash] = $name = $this->generateUniqueModelName($model); // not reserved yet
    $this->registeredModelNames[$name] = $model;

    $schema = $this->describeSchema($model, null);   // <-- recursion registers nested models here
    ...
}
...
Util::getSchema($this->api, $this->names[$hash]);    // <-- name reserved only now
```

`generateUniqueModelName()` derives uniqueness solely from `$this->api->components->schemas`
(`registeredModelNames` is only used for a log line), so a model registered during that recursive
probe is handed the very same generated name. Instrumenting `describeSchema()` in the reproducer:

```
describeSchema name=NULL       hash=cb8adb8f schema=#489   ctx=[]                        <- dedup probe, root model
describeSchema name=NULL       hash=5f4ee9f9 schema=#4409  ctx={"enable_max_depth":true} <- dedup probe, #[Context] variant (registered inside the recursion above)
describeSchema name='Category' hash=5f4ee9f9 schema=#2815  ctx={"enable_max_depth":true} <- registerSchemas()
describeSchema name='Category' hash=cb8adb8f schema=#2815  ctx=[]                        <- same name, same OA\Schema instance
```

**3. Consequence.** `registerSchemas()` describes both models into the *same* `OA\Schema` instance
(`Util::getSchema()` returns the existing one), so every property is merged twice. Scalar duplicates
merge silently, but a property whose attribute carries a nested annotation object hits the
`$currentValues[$property] !== $value` branch in `AbstractAnnotation::mergeProperties()` and logs the
error above. Beyond the crash, the emitted `Category` schema is the merge of two different
serialization contexts.

Part 2 is not new in 5.12.0 — `register()` is byte-identical in 5.11.1. 5.12.0 only makes the
duplicate model exist, which is what exposes the collision.

### JSON OpenApi

Not available — this *is* the bug: `nelmio:apidoc:dump` exits 1, so no documentation is produced.
With the fix below applied, the reproducer dumps `Category` and `Category2`.

#### Suggested fix

Reserve the generated name before the recursive dedup probe, e.g.:

```diff
         if (!isset($this->names[$hash])) {
             $this->names[$hash] = $name = $this->generateUniqueModelName($model);
             $this->registeredModelNames[$name] = $model;
+            Util::getSchema($this->api, $name); // reserve before recursive describe
 
             $schema = $this->describeSchema($model, null);
```

Verified against the reproducer and against a larger real-world application: the dump succeeds. If the dedup probe then matches an existing model, the reserved (empty) schema should
presumably be removed from `components.schemas` alongside the
`unset($this->names[$hash], $this->registeredModelNames[$name])` that already happens on that path —
or `generateUniqueModelName()` could consider `registeredModelNames` instead of only
`components.schemas`.

Worth noting separately: with that fix the reproducer emits `Category` **and** `Category2`, whose
JSON is identical, so the schema dedup added for this case does not collapse them (the probe schemas
are built at different times, before the nested names settle). Not fatal, but it means every
`#[Context]`-annotated self-reference now doubles its schema.

#### Workaround

Pin to 5.11.1 (`"conflict": { "nelmio/api-doc-bundle": "5.12.0" }`).

#### Possibly related

- #2745 — `JMSModelDescriber::computeGroups()` returning null for `['Default']` also ends in
  duplicate schema variants for one model. Different cause (JMS-only, and no crash), but it may be
  the same underlying "one model, two schemas" family; worth checking whether one fix covers both.

**Comment by DjordyKoert** [comment]
Thanks for the issue! should be fixed in next release https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v5.12.1 😄
