### ISSUE TITLE
Component\Swagger\Collections\Responses does not implement Countable

### ISSUE THREAD

**Issue by timotheemoulin** [nelmio/NelmioApiDocBundle#1116]
Hi all,
after upgrading from nelmio v2 to v3 I always get the following error

> Warning: count(): Parameter must be an array or an object that implements Countable
> in vendor/nelmio/api-doc-bundle/Describer/DefaultDescriber.php (line 41)

It runs on PHP 7.2 with Symfony 3

**Comment by wendel841** [comment]
+1 for this issue. Seems like php 7.2 issue with https://wiki.php.net/rfc/counting_non_countables

Can be fixed in DefaultDescriber.php line 41:
`if (0 === count($operation->getResponses())) {`

Should be:
`if (0 === iterator_count($operation->getResponses())) {`

**Comment by GuilhemN** [comment]
This issue has already been fixed https://github.com/nelmio/NelmioApiDocBundle/commit/da1c1e66f8461ae1a498248bd552d8f621f493bd.
